### ISSUE TITLE
Development discontinued?

### ISSUE THREAD

**Issue by stephanedaviet** [studentkittens/moosecat#1]
Hi,

I was exactly seeking for the kind of MPD client you were developing. « Were » : because I'm not sure there's still some work on it ?

Too bad as so many clients and so few good experiences… Sticking to the simple, unmaintained but efficient Sonata for now.

Hoping to be wrong.

**Comment by sahib** [comment]
Well, sorry to disappoint you. 

I currently have no time for moosecat, although I succesfully used the library behind it in [some](https://github.com/sahib/libmunin) [assignments](https://github.com/studentkittens/snobaer). I simply have too [many](https://github.com/sahib/rmlint) [other](https://github.com/disorganizer/brig) [projects](https://github.com/sahib/glyr) that need my attention - which doesn't mean I might come back to `moosecat` at some time. But that's not expected for the near future.

That said, the code base isn't too bad and the GUI can be done easily in Python/Gtk. If you, or someone else, want to take on it, I would be happy to answer questions.

_Edit_: A bit sad that this is the first opened issue...

**Comment by stephane-daviet-maif** [comment]
Thanks for the honesty. MPD is a great piece of software, but there is really a problem on frontend clients : too much choice with most of them that does not match expectation or are simply discontinued like yours. Yes, somebody can take the code and resurect your player, but I more surely thing that one n+1 will appear soon… It will be so much better if efforts were targeted on the development of one great extensible and customizable player, but you and me cannot make a lot about that.
